export var courses = [
{ id: 1, name: 'a', lecturer: 1, description: 'asddsa'},
{ id: 2, name: 'b', lecturer: 2, description: 'ads'},
{ id: 3, name: 'c', lecturer: 3, description: 'adsasdadsadssad'},
{ id: 4, name: 'd', lecturer: 4, description: 'asdaasddsasdadsadsdsa'},
{ id: 5, name: 'a', lecturer: 1, description: 'asdadsdasdsa'},
{ id: 6, name: 'b', lecturer: 2, description: 'acxzcczxcds'},
{ id: 7, name: 'c', lecturer: 3, description: 'ads123123adssad'},
{ id: 8, name: 'd', lecturer: 4, description: 'ascserewrdadsadsdsa'},
{ id: 9, name: 'a', lecturer: 1, description: 'asdasdfsdfdsa'},
{ id: 10, name: 'b', lecturer: 2, description: 'adggdssgds'},
{ id: 11, name: 'c', lecturer: 3, description: 'a12312dsadssad'},
{ id: 12, name: 'd', lecturer: 4, description: 'asdadsadsdsa'},
{ id: 13, name: 'a', lecturer: 1, description: 'asgsgfddsa'},
{ id: 14, name: 'b', lecturer: 2, description: 'addfgdf132s'},
{ id: 15, name: 'c', lecturer: 3, description: 'ads312312312dssad'},
{ id: 16, name: 'd', lecturer: 4, description: 'asd12312312adsadsdsa'},
{ id: 17, name: 'a', lecturer: 1, description: 'as123132ddsa'},
{ id: 18, name: 'b', lecturer: 2, description: 'ad123s'},
{ id: 19, name: 'c', lecturer: 3, description: 'ads123123adssad'},
{ id: 20, name: 'd', lecturer: 4, description: 'asda12312123dsadsdsa'},
]